#!/usr/bin/env bash
#
# Observer Vault: Merge Upstream Signal-Desktop
#
# This script helps automate merging new Signal-Desktop releases into Observer Vault.
# It handles common conflict patterns automatically and highlights files needing manual review.
#
# Usage:
#   ./scripts/merge-upstream.sh v7.88.0
#
# Prerequisites:
#   - You must have 'upstream' remote pointing to Signal-Desktop
#   - Working directory must be clean (no uncommitted changes)
#
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Files that should ALWAYS accept upstream version (no Observer Vault customizations)
AUTO_ACCEPT_UPSTREAM=(
    # Locale files - Observer Vault is not localized
    "_locales/*/messages.json"
    
    # Generated files - will be regenerated
    "ACKNOWLEDGMENTS.md"
    
    # Documentation we don't customize
    "CONTRIBUTING.md"
    "SECURITY.md"
    
    # Storybook (we don't customize)
    ".storybook/**"
    "sticker-creator/**"
)

# Files/directories from upstream that should be DELETED (not used in Observer Vault)
DELETE_FROM_UPSTREAM=(
    # Issue templates - we don't want Signal's issue templates
    ".github/ISSUE_TEMPLATE"
    
    # PR template - we have our own workflow
    ".github/PULL_REQUEST_TEMPLATE.md"
    
    # Dependabot - we manage dependencies manually
    ".github/dependabot.yml"
)

# Workflow files that should be DISABLED (renamed to .disabled)
# These are upstream workflows we don't run but keep for reference
DISABLE_WORKFLOWS=(
    ".github/workflows/backport.yml"
    ".github/workflows/benchmark.yml"
    ".github/workflows/commits.yml"
    ".github/workflows/danger.yml"
    ".github/workflows/icu-book.yml"
    ".github/workflows/notes.yml"
    ".github/workflows/release-notes.yml"
    ".github/workflows/release.yml"
    ".github/workflows/reproducible-build-scheduler.yml"
    ".github/workflows/reproducible-builds.yml"
    ".github/workflows/stories.yml"
)

# Files with Observer Vault customizations that MUST be reviewed manually
# Generated by: ./scripts/audit-customizations.sh
MANUAL_REVIEW_REQUIRED=(
    # Branding
    "package.json"
    
    # Observer Vault custom modules (always ours)
    "ts/observervault/**"
    
    # Background process customizations
    "ts/background.preload.ts"
    
    # Call quality survey (disabled)
    "ts/util/callQualitySurvey.dom.ts"
    
    # Registration/Install flow
    "ts/state/smart/InstallScreen.preload.tsx"
    "ts/components/installScreen/InstallScreenCreatingAccountStep.dom.tsx"
    
    # Files with @lockdown-systems/ringrtc imports
    "ts/calling/VideoSupport.preload.ts"
    "ts/calling/findBestMatchingDevice.std.ts"
    "ts/components/CallManager.dom.tsx"
    "ts/components/CallScreen.dom.tsx"
    "ts/components/CallingDeviceSelection.dom.tsx"
    "ts/components/CallingPip.dom.tsx"
    "ts/components/CallingPipRemoteVideo.dom.tsx"
    "ts/components/CallingLobby.dom.tsx"
    "ts/components/GroupCallOverflowArea.dom.tsx"
    "ts/components/GroupCallRemoteParticipant.dom.tsx"
    "ts/components/GroupCallRemoteParticipants.dom.tsx"
    "ts/components/Preferences.dom.tsx"
    "ts/components/GlobalModalContainer.dom.tsx"
    "ts/components/IncomingCallBar.dom.tsx"
    "ts/components/LeftPane.dom.tsx"
    "ts/components/ToastManager.dom.tsx"
    "ts/services/calling.preload.ts"
    "ts/state/ducks/calling.preload.ts"
    "ts/state/ducks/globalModals.preload.ts"
    "ts/state/ducks/conversations.preload.ts"
    "ts/state/smart/Preferences.preload.tsx"
    "ts/types/CallLink.std.ts"
    "ts/types/CallQualitySurvey.std.ts"
    "ts/types/Calling.std.ts"
    "ts/types/Storage.d.ts"
    "ts/util/callDisposition.preload.ts"
    "ts/util/callLinks/zkgroup.preload.ts"
    "ts/util/callLinksRingrtc.node.ts"
    "ts/util/callingMessageToProto.node.ts"
    "ts/util/callingPermissions.std.ts"
    "ts/util/onCallLinkUpdateSync.preload.ts"
    "ts/util/requestMicrophonePermissions.std.ts"
    "ts/util/queueAttachmentDownloads.preload.ts"
    
    # Build/config files referencing our fork
    "scripts/esbuild.js"
    "scripts/generate-acknowledgments.js"
    ".eslint/rules/file-suffix.js"
)

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in the right directory
check_repo() {
    if [[ ! -f "package.json" ]] || ! grep -q '"name": "observer-vault"' package.json 2>/dev/null; then
        log_error "This script must be run from the observer-vault repository root"
        exit 1
    fi
}

# Check for clean working directory
check_clean() {
    if [[ -n $(git status --porcelain) ]]; then
        log_error "Working directory is not clean. Commit or stash your changes first."
        exit 1
    fi
}

# Fetch upstream and verify tag exists
fetch_upstream() {
    local tag="$1"
    
    log_info "Fetching upstream..."
    git fetch upstream --tags
    
    if ! git rev-parse "$tag" >/dev/null 2>&1; then
        log_error "Tag '$tag' not found. Available recent tags:"
        git tag -l 'v7.*' | sort -V | tail -10
        exit 1
    fi
    
    log_success "Found tag $tag"
}

# Start the merge
start_merge() {
    local tag="$1"
    local branch="merge-${tag}"
    
    log_info "Creating merge branch: $branch"
    git checkout -b "$branch" 2>/dev/null || git checkout "$branch"
    
    log_info "Starting merge of $tag..."
    if git merge "$tag" --no-commit --no-ff 2>/dev/null; then
        log_success "Merge completed without conflicts!"
        return 0
    else
        log_warning "Merge has conflicts. Processing..."
        return 1
    fi
}

# Auto-accept upstream for specified file patterns
auto_accept_upstream() {
    log_info "Auto-accepting upstream for non-customized files..."
    
    local conflicts
    conflicts=$(git diff --name-only --diff-filter=U 2>/dev/null || true)
    
    if [[ -z "$conflicts" ]]; then
        log_info "No conflicts to auto-resolve"
        return 0
    fi
    
    local auto_resolved=0
    
    for pattern in "${AUTO_ACCEPT_UPSTREAM[@]}"; do
        # Find conflicting files matching this pattern
        local matching_files
        matching_files=$(echo "$conflicts" | grep -E "^${pattern//\*/.*}$" 2>/dev/null || true)
        
        if [[ -n "$matching_files" ]]; then
            while IFS= read -r file; do
                if [[ -n "$file" ]]; then
                    log_info "  Auto-accepting upstream: $file"
                    git checkout --theirs "$file" 2>/dev/null && git add "$file"
                    ((auto_resolved++)) || true
                fi
            done <<< "$matching_files"
        fi
    done
    
    log_success "Auto-resolved $auto_resolved files by accepting upstream"
}

# Handle package.json specially
handle_package_json() {
    if git diff --name-only --diff-filter=U | grep -q "^package.json$"; then
        log_warning "package.json has conflicts - applying Observer Vault branding..."
        
        # Get upstream version
        local upstream_version
        upstream_version=$(git show MERGE_HEAD:package.json | grep '"version"' | head -1 | sed 's/.*: *"\([^"]*\)".*/\1/')
        
        # Accept upstream first
        git checkout --theirs package.json
        
        # Apply Observer Vault branding
        local tmp_file=$(mktemp)
        cat package.json | \
            sed 's/"name": "signal-desktop"/"name": "observer-vault"/' | \
            sed 's/"productName": "Signal"/"productName": "Observer Vault"/' | \
            sed 's/"description": "Private messaging from your desktop"/"description": "Secure video call recorder for community observers"/' | \
            sed 's/"desktopName": "signal.desktop"/"desktopName": "observervault.desktop"/' | \
            sed 's|"repository": "https://github.com/signalapp/Signal-Desktop.git"|"repository": "https://github.com/micahflee/observer-vault.git"|' \
            > "$tmp_file"
        
        mv "$tmp_file" package.json
        
        # Remove @signalapp/ringrtc if present (we use @lockdown-systems/ringrtc)
        if grep -q '"@signalapp/ringrtc"' package.json; then
            log_info "  Removing @signalapp/ringrtc (we use @lockdown-systems/ringrtc)"
            # Use node to properly edit JSON
            node -e "
                const fs = require('fs');
                const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
                delete pkg.dependencies['@signalapp/ringrtc'];
                fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
            "
        fi
        
        git add package.json
        log_success "package.json updated with Observer Vault branding (version: $upstream_version)"
    fi
}

# Handle pnpm-lock.yaml
handle_lockfile() {
    if git diff --name-only --diff-filter=U | grep -q "^pnpm-lock.yaml$"; then
        log_info "Accepting upstream pnpm-lock.yaml (will regenerate with pnpm install)"
        git checkout --theirs pnpm-lock.yaml
        git add pnpm-lock.yaml
    fi
}

# Delete files/directories that upstream adds but we don't want
delete_unwanted_files() {
    log_info "Removing unwanted upstream files..."
    
    local deleted=0
    
    for path in "${DELETE_FROM_UPSTREAM[@]}"; do
        if [[ -e "$path" ]]; then
            log_info "  Deleting: $path"
            git rm -rf "$path" 2>/dev/null || rm -rf "$path"
            ((deleted++)) || true
        fi
    done
    
    if [[ $deleted -gt 0 ]]; then
        log_success "Deleted $deleted unwanted files/directories"
    else
        log_info "No unwanted files to delete"
    fi
}

# Disable upstream workflows by renaming to .disabled
disable_workflows() {
    log_info "Disabling upstream workflows..."
    
    local disabled=0
    
    for workflow in "${DISABLE_WORKFLOWS[@]}"; do
        if [[ -f "$workflow" ]]; then
            local disabled_name="${workflow}.disabled"
            log_info "  Disabling: $workflow -> $disabled_name"
            git mv "$workflow" "$disabled_name" 2>/dev/null || mv "$workflow" "$disabled_name"
            git add "$disabled_name" 2>/dev/null || true
            ((disabled++)) || true
        fi
    done
    
    if [[ $disabled -gt 0 ]]; then
        log_success "Disabled $disabled workflows"
    else
        log_info "No workflows to disable"
    fi
}

# Show remaining conflicts
show_remaining_conflicts() {
    local conflicts
    conflicts=$(git diff --name-only --diff-filter=U 2>/dev/null || true)
    
    if [[ -z "$conflicts" ]]; then
        log_success "All conflicts resolved!"
        return 0
    fi
    
    echo ""
    log_warning "The following files still have conflicts and need manual review:"
    echo ""
    
    while IFS= read -r file; do
        if [[ -n "$file" ]]; then
            # Check if it's a known customized file
            local is_known=false
            for pattern in "${MANUAL_REVIEW_REQUIRED[@]}"; do
                if [[ "$file" == $pattern ]] || [[ "$file" =~ ^${pattern//\*/.*}$ ]]; then
                    is_known=true
                    break
                fi
            done
            
            if $is_known; then
                echo -e "  ${YELLOW}[CUSTOMIZED]${NC} $file"
            else
                echo -e "  ${RED}[UNKNOWN]${NC} $file - may need investigation"
            fi
        fi
    done <<< "$conflicts"
    
    echo ""
    log_info "Tips for resolving remaining conflicts:"
    echo "  1. For files with Observer Vault customizations, carefully review both versions"
    echo "  2. Keep our custom imports (e.g., @lockdown-systems/ringrtc)"
    echo "  3. Keep our disabled features (e.g., call quality survey)"
    echo "  4. Accept upstream API changes but preserve our customizations"
    echo ""
    echo "After resolving, run:"
    echo "  git add <resolved-files>"
    echo "  pnpm install"
    echo "  pnpm generate"
    echo "  git commit"
    
    return 1
}

# Regenerate dependencies and build
regenerate() {
    log_info "Running pnpm install to regenerate lockfile..."
    pnpm install
    
    log_info "Running pnpm generate to verify build..."
    if pnpm generate; then
        log_success "Build successful!"
    else
        log_error "Build failed - check for issues"
        return 1
    fi
}

# Main
main() {
    if [[ $# -lt 1 ]]; then
        echo "Usage: $0 <upstream-tag>"
        echo "Example: $0 v7.88.0"
        exit 1
    fi
    
    local tag="$1"
    
    echo ""
    echo "=========================================="
    echo "  Observer Vault Upstream Merge Helper"
    echo "=========================================="
    echo ""
    
    check_repo
    check_clean
    fetch_upstream "$tag"
    
    if start_merge "$tag"; then
        # No conflicts - still need to handle deletions and disabled workflows
        delete_unwanted_files
        disable_workflows
        regenerate
        git add -A
        log_success "Ready to commit! Run: git commit"
    else
        # Handle conflicts
        auto_accept_upstream
        handle_package_json
        handle_lockfile
        delete_unwanted_files
        disable_workflows
        
        if show_remaining_conflicts; then
            # All resolved
            regenerate
            git add -A
            log_success "Ready to commit! Run: git commit"
        fi
    fi
}

main "$@"
